from __future__ import annotations


SEED_VERSION = 1


SEED_MENTORS = [
    {
        "name": "Aarav Mehta",
        "phone": "416-555-0101",
        "email": "aarav.mehta@demo-unisolved.ca",
        "program": "Computer Science",
        "year": 4,
        "languages": ["English", "Hindi"],
        "courses": ["CSC108", "CSC148", "MAT137"],
        "help_topics": ["assignments", "study habits", "exam prep"],
        "bio": "Upper-year CS mentor who likes breaking down tough first-year concepts into weekly plans.",
        "availability": "Weeknights after 6 PM",
    },
    {
        "name": "Maya Chen",
        "phone": "416-555-0102",
        "email": "maya.chen@demo-unisolved.ca",
        "program": "Computer Science",
        "year": 3,
        "languages": ["English", "Mandarin"],
        "courses": ["CSC108", "CSC165", "STA130"],
        "help_topics": ["concept clarity", "problem sets", "time management"],
        "bio": "CS specialist for students who need help building confidence before labs and quizzes.",
        "availability": "Tuesday and Thursday afternoons",
    },
    {
        "name": "Simran Kaur",
        "phone": "416-555-0103",
        "email": "simran.kaur@demo-unisolved.ca",
        "program": "Life Sciences",
        "year": 4,
        "languages": ["English", "Punjabi", "Hindi"],
        "courses": ["BIO120", "BIO130", "CHM135"],
        "help_topics": ["lab reports", "memorization", "exam prep"],
        "bio": "Life Sci mentor who helps students turn dense lecture notes into practical study routines.",
        "availability": "Most evenings",
    },
    {
        "name": "Daniel Okafor",
        "phone": "416-555-0104",
        "email": "daniel.okafor@demo-unisolved.ca",
        "program": "Mathematics",
        "year": 4,
        "languages": ["English"],
        "courses": ["MAT135", "MAT136", "MAT137"],
        "help_topics": ["proofs", "practice planning", "midterm recovery"],
        "bio": "Math mentor who focuses on diagnosing where a student gets stuck before giving new drills.",
        "availability": "Monday, Wednesday, Friday mornings",
    },
    {
        "name": "Leila Hassan",
        "phone": "416-555-0105",
        "email": "leila.hassan@demo-unisolved.ca",
        "program": "Engineering Science",
        "year": 4,
        "languages": ["English", "Arabic"],
        "courses": ["APS105", "MAT186", "CIV100"],
        "help_topics": ["heavy course loads", "design reports", "study systems"],
        "bio": "EngSci senior who helps students survive packed weeks without losing track of deadlines.",
        "availability": "Late afternoons",
    },
    {
        "name": "Sofia Alvarez",
        "phone": "416-555-0106",
        "email": "sofia.alvarez@demo-unisolved.ca",
        "program": "Rotman Commerce",
        "year": 3,
        "languages": ["English", "Spanish"],
        "courses": ["ECO101", "MAT133", "RSM100"],
        "help_topics": ["class expectations", "group work", "office hours prep"],
        "bio": "Commerce mentor who helps first-years ask sharper questions and plan around deadlines.",
        "availability": "Weekdays before 4 PM",
    },
    {
        "name": "Noah Patel",
        "phone": "416-555-0107",
        "email": "noah.patel@demo-unisolved.ca",
        "program": "Computer Science",
        "year": 2,
        "languages": ["English", "Gujarati"],
        "courses": ["CSC108", "CSC148", "MAT102"],
        "help_topics": ["debugging", "pair study", "assignment triage"],
        "bio": "Friendly second-year who is good for students who want a near-peer perspective.",
        "availability": "Evenings and weekends",
    },
    {
        "name": "Anika Bose",
        "phone": "416-555-0108",
        "email": "anika.bose@demo-unisolved.ca",
        "program": "Psychology",
        "year": 4,
        "languages": ["English", "Bengali"],
        "courses": ["PSY100", "STA220", "SOC100"],
        "help_topics": ["stress management", "study planning", "research papers"],
        "bio": "Psychology mentor who pairs practical study help with low-pressure accountability check-ins.",
        "availability": "Tuesday evenings and Sundays",
    },
    {
        "name": "Jason Li",
        "phone": "416-555-0109",
        "email": "jason.li@demo-unisolved.ca",
        "program": "Economics",
        "year": 4,
        "languages": ["English", "Mandarin"],
        "courses": ["ECO101", "ECO102", "MAT133"],
        "help_topics": ["problem sets", "lecture review", "catch-up plans"],
        "bio": "Economics mentor who helps students recover after missing a week or bombing a quiz.",
        "availability": "Weeknights",
    },
    {
        "name": "Fatima Ali",
        "phone": "416-555-0110",
        "email": "fatima.ali@demo-unisolved.ca",
        "program": "Political Science",
        "year": 4,
        "languages": ["English", "Urdu"],
        "courses": ["POL101", "ENG100", "HIS103"],
        "help_topics": ["writing support", "reading loads", "finding campus help"],
        "bio": "Humanities mentor who is especially good at helping students feel less lost in big classes.",
        "availability": "Afternoons except Friday",
    },
    {
        "name": "Lucas Martin",
        "phone": "416-555-0111",
        "email": "lucas.martin@demo-unisolved.ca",
        "program": "Mechanical Engineering",
        "year": 3,
        "languages": ["English", "French"],
        "courses": ["MIE100", "MAT186", "PHY180"],
        "help_topics": ["labs", "group projects", "calendar planning"],
        "bio": "Engineering mentor for students who need structure and realistic weekly goals.",
        "availability": "Monday and Thursday evenings",
    },
    {
        "name": "Priya Nair",
        "phone": "416-555-0112",
        "email": "priya.nair@demo-unisolved.ca",
        "program": "Nursing",
        "year": 4,
        "languages": ["English", "Malayalam", "Hindi"],
        "courses": ["NFS284", "PSL300", "HMB265"],
        "help_topics": ["wellness check-ins", "clinical prep", "balancing workload"],
        "bio": "Supportive mentor for students who are overwhelmed and need a calm next-step plan.",
        "availability": "Most weekends and Wednesday evenings",
    },
]


SEED_RESOURCES = [
    {
        "name": "Academic Success Centre",
        "category": "academic_support",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Academic skills support for study strategy, time management, note-taking, and exam preparation.",
        "tags": ["academics", "study skills", "assignments", "time management", "exam prep"],
        "source_url": "https://studentlife.utoronto.ca/service/academic-success/",
        "is_official": True,
    },
    {
        "name": "Health & Wellness Centre",
        "category": "wellness",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Official health and wellness support for mental health, urgent concerns, and same-day student care options.",
        "tags": ["stress", "mental health", "wellness", "overwhelmed", "support"],
        "source_url": "https://studentlife.utoronto.ca/service/health-wellness/",
        "is_official": True,
    },
    {
        "name": "Writing Centres",
        "category": "writing_support",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Writing support for essays, reports, argument structure, and revision planning.",
        "tags": ["writing", "essays", "reports", "feedback"],
        "source_url": "https://writing.utoronto.ca/",
        "is_official": True,
    },
    {
        "name": "Accessibility Services",
        "category": "accessibility",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Official support for academic accommodations, accessibility planning, and student documentation processes.",
        "tags": ["accommodations", "accessibility", "documentation", "support"],
        "source_url": "https://studentlife.utoronto.ca/service/accessibility-services/",
        "is_official": True,
    },
    {
        "name": "Registrar and Records",
        "category": "administrative",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Official registrar guidance for enrolment, deadlines, transcripts, petitions, and academic records.",
        "tags": ["registrar", "deadline", "enrolment", "petition", "records", "tuition"],
        "source_url": "https://future.utoronto.ca/finances/registrar/",
        "is_official": True,
    },
    {
        "name": "Sidney Smith Commons",
        "category": "student_support",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Central student hub with advising access, support navigation, and referrals to campus services.",
        "tags": ["student life", "support", "advising", "campus help"],
        "source_url": "https://studentlife.utoronto.ca/department/student-life-programs-services/",
        "is_official": True,
    },
    {
        "name": "Math Learning Centre",
        "category": "academic_support",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Math-focused academic help for calculus, proof-based courses, and quantitative study support.",
        "tags": ["math", "calculus", "proofs", "problem sets"],
        "source_url": "https://www.math.toronto.edu/cms/undergraduate-program/current-students-ug/math-learning-centre/",
        "is_official": True,
    },
    {
        "name": "Career Exploration & Education",
        "category": "career",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Career centre support for resumes, networking, interviews, and planning next academic or career steps.",
        "tags": ["career", "resume", "interviews", "networking"],
        "source_url": "https://studentlife.utoronto.ca/department/career-learning-network/",
        "is_official": True,
    },
    {
        "name": "UTSU Food Bank",
        "category": "student_support",
        "campus": "U of T St. George",
        "area": "St. George",
        "description": "Student-run food support service for U of T students who need help with groceries and essentials.",
        "tags": ["food support", "student support", "essentials"],
        "source_url": "https://www.utsu.ca/services/food-bank/",
        "is_official": False,
    },
]


SEED_RESTAURANTS = [
    {
        "name": "Future Bistro",
        "category": "restaurant",
        "campus": "U of T St. George",
        "area": "Bloor and Brunswick",
        "description": "Casual Annex spot for late meals, coffee, and study-friendly booth seating.",
        "tags": ["food", "late night", "study break", "casual"],
        "source_url": "https://futurebistro.com/",
        "is_official": False,
    },
    {
        "name": "The Madison Avenue Pub",
        "category": "restaurant",
        "campus": "U of T St. George",
        "area": "Madison Avenue",
        "description": "Large pub close to campus that works well for group meetups after class.",
        "tags": ["food", "groups", "after class", "casual"],
        "source_url": "https://madisonavenuepub.com/",
        "is_official": False,
    },
    {
        "name": "Fresh on Bloor",
        "category": "restaurant",
        "campus": "U of T St. George",
        "area": "Bloor Street West",
        "description": "Vegetarian-friendly option near campus with quick bowls, wraps, and smoothies.",
        "tags": ["food", "vegetarian", "quick meal", "healthy"],
        "source_url": "https://www.freshkitchens.ca/",
        "is_official": False,
    },
    {
        "name": "Banh Mi Boys",
        "category": "restaurant",
        "campus": "U of T St. George",
        "area": "Bloor and Spadina",
        "description": "Fast casual option for a quick meal between classes near the downtown campus core.",
        "tags": ["food", "quick meal", "takeout", "between classes"],
        "source_url": "https://banhmiboys.com/",
        "is_official": False,
    },
]
